"""Tests for recorded-truth Fossen auto-calibration (roadmap #46).

The central guarantee: fed truth generated by the model with *known* parameters,
the fitter recovers those parameters. That both proves the machinery works and
sets the honest ceiling (real data has noise/unmodelled physics, so this is the
best case, not the typical one).
"""

from __future__ import annotations

import numpy as np
import pytest

pytest.importorskip("scipy")  # the calibrate module fits via scipy.optimize

from vanchor.analysis.fossen_calibrate import (
    CalibrationResult,
    Recording,
    RecordedSample,
    calibrate_fossen,
    default_param_base,
    simulate_recording,
)
from vanchor.core.models import Environment, GeoPoint
from vanchor.sim.fossen import FossenParams

# A maneuver that excites both the surge terms (a straight accelerate-to-top-
# speed leg) and the yaw terms (a hard sustained turn). Without the turn, yaw
# damping is unidentifiable; without the straight leg, top speed is.
MANEUVER = [
    (0.0, 0.9, 0.0),  # full ahead, straight -> top speed + thrust scale
    (20.0, 0.7, 0.85),  # hard starboard turn -> yaw damping / turn response
]


def _truth(params: FossenParams) -> Recording:
    return simulate_recording(
        params, MANEUVER, duration_s=40.0, dt=0.1, start_heading_deg=10.0
    )


def test_default_param_base_is_raw_defaults():
    base = default_param_base()
    # Raw, pre-__post_init__ values (n_r is scaled in place by __post_init__).
    assert base["n_r"] == -700.0
    assert base["max_thrust_n"] == 250.0
    assert base["max_speed_mps"] == 1.6
    # Every fittable float field is present.
    assert base["y_v"] == -260.0


def test_simulate_recording_shape_and_motion():
    rec = simulate_recording(FossenParams(), MANEUVER, duration_s=10.0, dt=0.1)
    assert isinstance(rec, Recording)
    assert len(rec.samples) == 101  # duration/dt + 1
    assert rec.samples[0].t == 0.0
    # The boat actually accelerated under full thrust.
    assert rec.samples[-1].speed_mps > rec.samples[0].speed_mps + 0.3


def test_recording_needs_two_samples():
    with pytest.raises(ValueError):
        Recording(samples=[])


def test_calibrate_rejects_unknown_field():
    rec = _truth(FossenParams())
    with pytest.raises(ValueError):
        calibrate_fossen(rec, ["not_a_real_param"])
    with pytest.raises(ValueError):
        calibrate_fossen(rec, [])


def test_recovers_known_params_from_synthetic_truth():
    """The headline test: recover ground-truth params from model-generated truth."""
    true = FossenParams(max_thrust_n=310.0, max_speed_mps=1.95, n_r=-920.0)
    rec = _truth(true)

    names = ["max_thrust_n", "max_speed_mps", "n_r"]
    result = calibrate_fossen(rec, names)

    assert isinstance(result, CalibrationResult)
    assert result.success
    # Started from the (deliberately wrong) model defaults...
    assert result.initial["max_thrust_n"] == 250.0
    # ...and converged onto the true generating values.
    assert result.fitted["max_thrust_n"] == pytest.approx(310.0, rel=0.05)
    assert result.fitted["max_speed_mps"] == pytest.approx(1.95, rel=0.02)
    assert result.fitted["n_r"] == pytest.approx(-920.0, rel=0.05)
    # A near-perfect replay: residuals collapse to ~0.
    assert result.residual_rms < 1e-2


def test_calibrated_params_reproduce_the_run():
    """result.params() rebuilds a FossenParams that replays the recording."""
    true = FossenParams(max_thrust_n=280.0, max_speed_mps=1.75, n_r=-820.0)
    rec = _truth(true)

    result = calibrate_fossen(rec, ["max_thrust_n", "max_speed_mps", "n_r"])
    fitted_params = result.params()

    replay = _truth(fitted_params)
    # Final position matches the recorded truth to well under a metre.
    from vanchor.core.geo import haversine_m

    err = haversine_m(replay.samples[-1].point, rec.samples[-1].point)
    assert err < 1.0


def test_recovers_from_environment_run():
    """Calibration replays the logged environment, so wind doesn't corrupt the fit."""
    env = Environment(wind_speed=4.0, wind_dir=120.0, current_speed=0.2, current_dir=45.0)
    true = FossenParams(max_thrust_n=300.0, max_speed_mps=1.8, n_r=-880.0)
    rec = simulate_recording(
        true, MANEUVER, duration_s=40.0, dt=0.1, start_heading_deg=10.0, environment=env
    )
    result = calibrate_fossen(rec, ["max_thrust_n", "max_speed_mps", "n_r"])
    assert result.fitted["max_speed_mps"] == pytest.approx(1.8, rel=0.04)
    assert result.fitted["n_r"] == pytest.approx(-880.0, rel=0.08)


def test_manual_recording_from_samples():
    """A Recording can be built from hand-assembled samples (real-logger shape)."""
    p0 = GeoPoint(59.0, 18.0)
    samples = [
        RecordedSample(t=0.0, thrust=0.5, steering=0.0, point=p0, heading_deg=0.0, speed_mps=0.0),
        RecordedSample(
            t=0.1, thrust=0.5, steering=0.0, point=GeoPoint(59.0000009, 18.0),
            heading_deg=0.0, speed_mps=0.1,
        ),
    ]
    rec = Recording(samples=samples)
    # Fitting a single well-excited surge param on a 2-sample run must not crash
    # and must stay within bounds.
    result = calibrate_fossen(rec, ["max_thrust_n"], max_nfev=50)
    lo, hi = 0.2 * 250.0, 5.0 * 250.0
    assert lo <= result.fitted["max_thrust_n"] <= hi
    assert np.isfinite(result.residual_rms)
