# This is a basic workflow that is manually triggered

name: Release

env:
  runNumber: ${{ github.run_number }}
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create-artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Create ZIP
        run: cd src && zip -r "../vanchor.zip" . && cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: vanchor-${{ env.runNumber }}
          path: vanchor.zip
